### PR TITLE
Smarter parsing of content type

### PR DESCRIPTION
**Pull request by xprl-gjf**
Proposed implementation for enahncement #20

Matched received content-type against 'accept' headers, making it possible to take account of custom content-types.
Performs optimistic matching with respect to media-type parameter options.
Included updated unit tests.

### CODE REVIEW

**Comment by xprl-gjf** [comment]
Oops - because I have merged my previous pull requests into my fork of 'next', they are also included in this pull request.
What would you prefer I do - cancel this pull request and create a specific feature branch, or would you cherry-pick commits aa1a4f0 and bd42fdb

Sorry - just getting started with Git / GitHub, so still learning.

**Comment by xprl-gjf** [comment]
I now realise that there is an assumption that all content types accepted by the client are parse-able HAL, and of course this might not be the case... so back to your suggestion of registering types.

Can I propose the following:
- Add a 'hal' parameter to Navigator.hal that accepts a list of parse-able hal types
- By default, assume that all types in the 'Accept' header field are parse-able, so default 'hal' with all types in the 'Accept' header. If not all types are considered parse-able, then the user must explicitly provide the list of parse-able types.

This leads to the following usage:
1. typical, with default headers and therefore application/hal+json and application/json types parsed as HAL:

``` python
N = Navigator.hal("www.example.com", "api")
```
1. client expecting some non-hal content:

``` python
N=Navigator.hal("www.example.com", "api", headers={'Accept': 'application/xml, application/hal+json, application/json'}, hal=['application/hal+json', 'application/json'])
```
1. client expecting custom HAL format; all accepted types considered to be valid HAL

``` python
N=Navigator.hal("www.example.com", "api", headers={'Accept': 'application/vnd.custom.format, application/hal+json, application/json'})
```
1. client expecting custom HAL format and some non-HAL content:

``` python
N=Navigator.hal("www.example.com", "api", headers={'Accept': 'application/xml, application/vnd.custom.format, application/hal+json'}, hal=['application/vnd.custom.format', 'application/hal+json'])
```

The least convenient case is case 2, where it might be more convenient if the caller does not need to list all the default hal formats. On the other hand, this allows clients to 'unregister' application/json as a HAL format if desired (although this is unlikely)...
A client could easily construct the list of hal types themselves via something like:

``` python
headers={'Accept': 'application/xml,application/hal+json,application/json'}
hal_types=filter(lambda t: t.endswith('json'), headers['Accept'].split(','))
N=Navigator.hal("www.example.com", "api", headers=headers, hal=hal_types)
```

I can add this implementation into my pull request (once I sort my branches out :) )

**Comment by deontologician** [comment]
Ultimately, I think this will need to be integrated with hooks (#13). That will provide a more flexible interface for specifying how to handle incoming content types. I think it's a bit too early for this functionality since the hooks aren't in place yet

**Comment by deontologician** [comment]
OK, I'm heartily impressed with this PR. It's of exceptional quality and thoughtfulness, and well tested. Accepting

**Comment by deontologician** [comment]
@bbsgfalconer I've added you as a collaborator on this repo. So if you feel like contributing in the future you can create branches etc directly in the main repo. (Use these powers wisely!)

**Comment by xprl-gjf** [comment]
Thanks Josh - I am honoured!
I will try to be careful :)

**Pull request merged**
