### PR TITLE
Allow easy POST with no body

### PR DESCRIPTION
**Pull request by xprl-gjf**
I'm working with a web application that accepts POST requests with no body.
To make this easier, specify a default of None for body in HALNavigator.create()

### CODE REVIEW

**Comment by deontologician** [comment]
This looks fine, I just want to write a test for it

**Comment by deontologician** [comment]
Would you mind splitting out the content-type negotiation into its own PR?

**Comment by xprl-gjf** [comment]
Sorry - I realise now that I should have submitted this pull request from a distinct branch...

Do you want me to re-submit a new pull request, or would you prefer to cherry-pick commit 9c54803

**Comment by deontologician** [comment]
Could you just `rebase -i` this branch onto the current next?

**Comment by xprl-gjf** [comment]
rebased

**Comment by deontologician** [comment]
awesome! I will check this out tonight.

**Comment by deontologician** [comment]
OK, merging. I created #30 to track testing this

**Pull request merged**
