### PR TITLE
Fixed a bug where embedded navgiators made unnessecary http requests.

### PR DESCRIPTION
**Pull request by tspng**
Looked like a simple fix, hope it's correct.

### CODE REVIEW

**Comment by deontologician** [comment]
This is beautiful, thank you very much for the pull request. I'll do a point release with these fixes today.

**Comment by deontologician** [comment]
OK, release is out: https://github.com/deontologician/restnavigator/releases/tag/v1.0.1 . I made an annoucement on hal-discuss. Thanks @haestan and @bubenkoff for your help

**Comment by bubenkoff** [comment]
Didn't do anything :)
Thanks to all who did!

**Comment by deontologician** [comment]
@bubenkoff Well, the sphinx stuff went out in this version

**Pull request merged**
